FROM node:22.17-alpine
WORKDIR /app
# Instalar dependencias
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install

# Copiar el resto del código y construir
COPY . .
RUN DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" npx prisma generate
RUN npm run build

EXPOSE 3000

# Usar el script de producción
CMD ["npm", "run", "start:prod"]
